server:
  port: 8081

spring:
  application:
    name: "prueba"


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect